### ISSUE TITLE
Column missing from docs

### ISSUE THREAD

**Issue by JosueCarrillo** [alfonsobries/laravel-spreadsheet-importer#1]
While using the system i got this error on my laravel log

![image](https://user-images.githubusercontent.com/24302233/67427232-579da600-f5a1-11e9-8388-72363b1de8bb.png)

I guess importable_error_message columns is missing from the docs on **Add the neccesary columns to the Importable Model** section.

Thanks in advance

**Comment by alfonsobries** [comment]
Fixed thanks @JosueCarrillo
